# Generated by Django 3.2.17 on 2023-03-16 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_brand_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fashion',
            field=models.CharField(choices=[('UNISSEX', 'Unissex'), ('FEMININA', 'Feminina'), ('MASCULINA', 'Masculina')], default='', max_length=50, verbose_name='Moda'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Data Cadastro'),
        ),
    ]
